### PR TITLE
Updated useful links in the supporting DB features tree

### PR DESCRIPTION
**Pull request by SyNuOra**
Added some blog posts to the useful links area

### CODE REVIEW

**Review by colivares1974 — DISMISSED** [review]
And now reviewing and approving 715

**Comment by AlexanderHodicke** [comment]
@colivares1974 and @SyNuOra if you approve a PR, please click right away on 'Merge pull request', then confirm it, and lastly to the right, delete the branch. Thanks!

**Comment by SyNuOra** [comment]
Managed conflict , submitting for re-approval

**Review by colivares1974 — APPROVED** [review]
Reviewed and approved

**Pull request merged**
