### PR TITLE
ODA folder

### PR DESCRIPTION
**Pull request by anshoracle**
ODA folder created

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Review by al3xne — CHANGES_REQUESTED** [review]
please update readme.md for ODA; description now refers to OCI AI Services, not specifically to ODA. Add links to oracle.com and architecture center - similar to the rest of AI Services

**Review by al3xne — DISMISSED** [review]

**Comment by al3xne** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by al3xne** [comment]
recheck

**Comment by anshoracle** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by anshoracle** [comment]
recheck

**Comment by anshoracle** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by al3xne — APPROVED** [review]

**Pull request merged**
