### PR TITLE
Adding new asset 'Solution definition'.

### PR DESCRIPTION
**Pull request by greiz00**
Solution definition for Hyperion in markdown, including drawio file with example diagrams.
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by greiz00** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by greiz00** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by greiz00** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by velrajkuppu — APPROVED** [review]
Reviewed

**Pull request merged**
