### PR TITLE
Updated Structure and added new future content areas

### PR DESCRIPTION
**Pull request by SyNuOra**
After discussions in the team for topics related to Database DevOps, the content structure and areas have been updated inline with terms and topics used by developers.

READMEs have been added to be updated by each responsible team member. This will allow each member to have the agreed structure updated.

### CODE REVIEW

**Review by colivares1974 — APPROVED** [review]
Reviewed and approved

**Comment by SyNuOra** [comment]
Hi Carlos,

The next branch merged before this one, so I need to re-re-resubmit this again :) after fixing the conflicts

**Review by colivares1974 — APPROVED** [review]
REviewing and approving 703

**Comment by AlexanderHodicke** [comment]
@colivares1974 again, feel free to merge the PR if you approved it

**Pull request merged**
