### PR TITLE
Hyperion discovery questionnaire

### PR DESCRIPTION
**Pull request by greiz00**
Discovery questionnaire for Hyperion.

### CODE REVIEW

**Comment by greiz00** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by greiz00** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by velrajkuppu — APPROVED** [review]
Approved

**Comment by velrajkuppu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
