### PR TITLE
Added new files for OAC

### PR DESCRIPTION
**Pull request by amittyagioracle**
Added following documents:-

1. OAC Private Access Channel
2. OAC Scaling Automation
3. OAC Email Setup

### CODE REVIEW

**Review by amittyagioracle — COMMENTED** [review]
Updated OAC PAC and OAC Scaling Document

**Review by amittyagioracle — COMMENTED** [review]
Please review updated PAC and OAC Scaling Document.

**Review by esmeralda-simionescu — APPROVED** [review]
Document changes to PAC and Email Setup implemented

**Comment by esmeralda-simionescu** [comment]
complete

**Pull request merged**
