### PR TITLE
Added multicloud assests by Ejaz

### PR DESCRIPTION
**Pull request by Ej4z4K**

### CODE REVIEW

**Comment by Ej4z4K** [comment]
test

**Review by AlexanderHodicke — CHANGES_REQUESTED** [review]
You need to accept the CLA, please comment on the PR main page at the bottom with

I have read the CLA Document and I hereby sign the CLA

I think the structure of your files is a little strange please follow my confluence guidance

**Comment by Ej4z4K** [comment]
recheck

**Comment by Ej4z4K** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Ej4z4K** [comment]
recheck

**Comment by Ej4z4K** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Ej4z4K** [comment]
recheck

**Comment by Ej4z4K** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Ej4z4K** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Ej4z4K** [comment]
recheck

**Review by vgarbuglio — COMMENTED** [review]
all good

**Pull request merged**
