### PR TITLE
Pull request to update OCI compute-hardware

### PR DESCRIPTION
**Pull request by mariusscholtz**
Created new content for OCI compute-hardware: OCI Compute shape naming convention. Also replaced confidential compute link with public link (it was pointing to Confluence).

### CODE REVIEW

**Comment by mariusscholtz** [comment]
Created new content for OCI compute-hardware: OCI Compute shape naming convention. Also replaced confidential compute link with public link (it was pointing to Confluence).

**Comment by mariusscholtz** [comment]
Created new content for OCI compute-hardware: OCI Compute shape naming convention. Also replaced confidential compute link with public link (it was pointing to Confluence).

**Comment by mariusscholtz** [comment]
Created new content for OCI compute-hardware: OCI Compute shape naming convention. Also replaced confidential compute link with public link (it was pointing to Confluence).

**Review by cagatay-cebi — APPROVED** [review]

**Comment by cagatay-cebi** [comment]
Approved

**Pull request merged**
