### PR TITLE
python-workshop

### PR DESCRIPTION
**Pull request by javidel**

### CODE REVIEW

**Review by AlexanderHodicke — COMMENTED** [review]
@oheimburger can you review the code please

**Review by oheimburger — CHANGES_REQUESTED** [review]
Hardcoded default passwords are present!
This violates Oracle policy (no password).

Change the code and the documentation to require user provided password.

This branch should be deleted.

**Comment by javidel** [comment]
Just replaced the password with: YOUR_PASSWORD.

Thanks for the feedback,
Javier

[Oracle]<http://www.oracle.com/>
Javier de la Torre, Principal Data Management Cloud Specialist
Mobile: +34 617 365 860
Specialist Cloud Engineering
Parque Tecnológico de Andalucía, C/Severo Ochoa 55 Campanillas

From: oheimburger ***@***.***>
Sent: Wednesday, November 22, 2023 2:03 PM
To: oracle-devrel/technology-engineering ***@***.***>
Cc: Javier de la Torre Medina ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [oracle-devrel/technology-engineering] python-workshop (PR #612)


@oheimburger requested changes on this pull request.

Hardcoded default passwords are present!
This violates Oracle policy (no password).

Change the code and the documentation to require user provided password.

This branch should be deleted.

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab1_prepare_environment.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402004521__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36G2inbylQ$>:

> +

+=========== Install and configure 23c free ========

+

+Obtain all the information for Oracle 23c Developer Free here: https://www.oracle.com/uk/database/free/get-started/

+

+1. Install Oracle 23c Developer free as root:

+

+sudo su

+wget https://yum.oracle.com/repo/OracleLinux/OL8/developer/x86_64/getPackage/oracle-database-preinstall-23c-1.0-0.5.el8.x86_64.rpm

+wget https://download.oracle.com/otn-pub/otn_software/db-free/oracle-database-free-23c-1.0-1.el8.x86_64.rpm

+yum -y localinstall oracle-database*

+

+2.- Configure Oracle 23c free

+

+/etc/init.d/oracle-free-23c configure

+--We are going to use this password: PassworD123##

No Password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab1_prepare_environment.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402004937__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GDiskZQQ$>:

> +echo 'export PATH=$ORACLE_HOME/bin:$PATH' >> .bashrc

+. .bashrc

+

+

+4.- Enable firewall and automatic start of 23c Database.

+

+systemctl enable oracle-free-23c

+firewall-cmd --permanent --add-port=1521/tcp

+firewall-cmd --reload

+

+

+========== Create new user for 23c  ==============

+

+

+sqlplus ***@***.***:1521/FREEPDB1 as sysdba

+create user myapp identified by PassworD123##;

No password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab2_first_steps.py<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402005251__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36ElBOrRZA$>:

> @@ -0,0 +1,20 @@

+import oracledb

+

+#thick mode for SODA

+oracledb.init_oracle_client()

+

+#connection details

+connection = oracledb.connect(user="myapp",password="PassworD123##",dsn="localhost:1521/FREEPDB1")

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab3_crud_operations.py<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402005592__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GB00fJuA$>:

> @@ -0,0 +1,244 @@

+import oracledb

+

+

+#connect with thick-client

+oracledb.init_oracle_client()

+connection = oracledb.connect(user="myapp",

+                              password="PassworD123##",

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab4_query_by_example.py<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402007046__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36HOChrcFQ$>:

> @@ -0,0 +1,49 @@

+import oracledb

+

+

+#connect with thick-client

+oracledb.init_oracle_client()

+connection = oracledb.connect(user="myapp",

+                              password="PassworD123##",

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab5_indexing.py<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402007652__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36G8dvXT7A$>:

> @@ -0,0 +1,56 @@

+import oracledb

+import json

+

+#connect with thick-client

+oracledb.init_oracle_client()

+connection = oracledb.connect(user="myapp",

+                              password="PassworD123##",

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab6_dbactions.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402008148__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GouwEEYg$>:

> +  Enter a number to select the database pool to update, or create an additional database pool.

+  The selected (or created) database pool will be used to install or upgrade ORDS in the database.

+    [1] default      jdbc:oracle:thin:@//localhost:1521/FREEPDB1

+    [2] Create an additional database pool

+  Choose [1]: 1

+  Enter a number to select the database connection type to use

+    [1] Basic (host name, port, service name)

+    [2] TNS (TNS alias, TNS directory)

+    [3] Custom database URL

+  Choose [1]: 1

+  Enter the database host name [localhost]:

+  Enter the database listen port [1521]:

+  Enter the database service name [FREEPDB1]:

+  Provide database user name with administrator privileges.

+    Enter the administrator username: SYS

+  Enter the database password for SYS AS SYSDBA: PassworD123##

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab6_dbactions.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402008549__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36G-veJRKg$>:

> +/

+

+exit;

+

+============== Configure the MongoDB API for later usage and Start ORDS ==============

+

+su - oracle

+ords config set mongo.enabled true

+cd /tmp

+nohup ords serve >> ords_log.log 2>&1 &

+

+

+-- Go to your browser and connect.

+http://PUBLIC_IP:8080/ords/sql-developer<https://urldefense.com/v3/__http:/PUBLIC_IP:8080/ords/sql-developer__;!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36Hnnii38A$>

+user: myapp

+password:PassworD123##

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab7_data_modeling.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402008825__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36FG9qDSJw$>:

> @@ -0,0 +1,323 @@

+============== 1) Working with SODA ==============

+

+Simple Oracle Document Access (SODA) is a set of NoSQL-style APIs that let you create and store collections of documents (in particular JSON) in Oracle Database, retrieve them, and query them, without needing to know Structured Query Language (SQL) or how the documents are stored in the database.

+

+How is data stored? Let's connect via sqlplus with root user.

+

+sqlplus ***@***.***:1521/FREEPDB1

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab7_data_modeling.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402009075__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36HBknJXxw$>:

> +When creating a SODA collection, a table is created. This table contains 4 columns for metadata, and 1 column containing the JSON information, DATA.

+

+

+2) select * from HOTEL_RESERVATIONS;

+

+We can run a select all and we can see all the information, including the JSON data. On the following lab, you will learn how to use SQL over JSON data.

+

+

+

+

+============== 2) Hybrid Model ==============

+

+We can create a table containing JSON data and relational data.

+

+

+sqlplus ***@***.***:1521/FREEPDB1

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab6_dbactions.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402010438__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36HUTkkEqQ$>:

> +  Choose [1]:

+  Enter the HTTP port [8080]:

+

+--When you see the following line, run: ctrl + c to kill ords

+

+2023-11-17T14:56:13.685Z INFO        Oracle REST Data Services initialized

+ctrl + c

+

+-- Open firewall

+exit

+firewall-cmd --permanent --zone=public --add-port=8080/tcp

+firewall-cmd --reload

+

+

+-- Enable myapp user for ORDS

+sqlplus ***@***.***:1521/FREEPDB1 as sysdba

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab7_data_modeling.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402010772__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36Gv7d3Yag$>:

> +

+

+==========================Map duality view to a python soda collection ============

+DECLARE col soda_collection_t;

+BEGIN

+  col := DBMS_SODA.create_dualv_collection('BILLING_COLLECTION', 'BILLING_DV');

+END;

+/

+============= New python code to work with collection ================

+import oracledb

+

+#thick mode for SODA

+oracledb.init_oracle_client()

+

+#connection details

+connection = oracledb.connect(user="myapp",password="PassworD123##",dsn="localhost:1521/FREEPDB1")

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab9_mongodb_api.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402011028__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36FLBThuMQ$>:

> @@ -0,0 +1,64 @@

+========================== Use MongoDB API with Duality views ============

+

+--Install mongodb client: https://www.mongodb.com/try/download/shell<https://urldefense.com/v3/__https:/www.mongodb.com/try/download/shell__;!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GH4-TVHw$>

+

+

+wget https://downloads.mongodb.com/compass/mongodb-mongosh-2.0.2.x86_64.rpm<https://urldefense.com/v3/__https:/downloads.mongodb.com/compass/mongodb-mongosh-2.0.2.x86_64.rpm__;!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GCqDIN_A$>

+yum localinstall mongodb-mongosh-2.0.2.x86_64.rpm

+

+--we can find the url at the ords log we defined before, and we will have something like this:

+--mongodb://[{user}:{password}@]localhost:27017/{user}?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true

+

+--It is a default string. Let's connect with our user.

+--For the password is required to change # with %23: https://docs.oracle.com/en-us/iaas/autonomous-database-serverless/doc/mongo-using-oracle-database-api-mongodb.html

+

+mongosh --tlsAllowInvalidCertificates ***@***.***:27017/myapp?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true'

No hardcoded password!

**Comment by javidel** [comment]
Hi,

Any update on this?

Javier

[Oracle]<http://www.oracle.com/>
Javier de la Torre, Principal Data Management Cloud Specialist
Mobile: +34 617 365 860
Specialist Cloud Engineering
Parque Tecnológico de Andalucía, C/Severo Ochoa 55 Campanillas

From: Javier de la Torre Medina
Sent: Wednesday, November 22, 2023 3:51 PM
To: oracle-devrel/technology-engineering ***@***.***>; oracle-devrel/technology-engineering ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [External] : Re: [oracle-devrel/technology-engineering] python-workshop (PR #612)

Just replaced the password with: YOUR_PASSWORD.

Thanks for the feedback,
Javier

[Oracle]<http://www.oracle.com/>
Javier de la Torre, Principal Data Management Cloud Specialist
Mobile: +34 617 365 860
Specialist Cloud Engineering
Parque Tecnológico de Andalucía, C/Severo Ochoa 55 Campanillas

From: oheimburger ***@***.******@***.***>>
Sent: Wednesday, November 22, 2023 2:03 PM
To: oracle-devrel/technology-engineering ***@***.******@***.***>>
Cc: Javier de la Torre Medina ***@***.******@***.***>>; Author ***@***.******@***.***>>
Subject: [External] : Re: [oracle-devrel/technology-engineering] python-workshop (PR #612)


@oheimburger requested changes on this pull request.

Hardcoded default passwords are present!
This violates Oracle policy (no password).

Change the code and the documentation to require user provided password.

This branch should be deleted.

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab1_prepare_environment.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402004521__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36G2inbylQ$>:

> +

+=========== Install and configure 23c free ========

+

+Obtain all the information for Oracle 23c Developer Free here: https://www.oracle.com/uk/database/free/get-started/

+

+1. Install Oracle 23c Developer free as root:

+

+sudo su

+wget https://yum.oracle.com/repo/OracleLinux/OL8/developer/x86_64/getPackage/oracle-database-preinstall-23c-1.0-0.5.el8.x86_64.rpm

+wget https://download.oracle.com/otn-pub/otn_software/db-free/oracle-database-free-23c-1.0-1.el8.x86_64.rpm

+yum -y localinstall oracle-database*

+

+2.- Configure Oracle 23c free

+

+/etc/init.d/oracle-free-23c configure

+--We are going to use this password: PassworD123##

No Password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab1_prepare_environment.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402004937__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GDiskZQQ$>:

> +echo 'export PATH=$ORACLE_HOME/bin:$PATH' >> .bashrc

+. .bashrc

+

+

+4.- Enable firewall and automatic start of 23c Database.

+

+systemctl enable oracle-free-23c

+firewall-cmd --permanent --add-port=1521/tcp

+firewall-cmd --reload

+

+

+========== Create new user for 23c  ==============

+

+

+sqlplus ***@***.***:1521/FREEPDB1 as sysdba

+create user myapp identified by PassworD123##;

No password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab2_first_steps.py<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402005251__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36ElBOrRZA$>:

> @@ -0,0 +1,20 @@

+import oracledb

+

+#thick mode for SODA

+oracledb.init_oracle_client()

+

+#connection details

+connection = oracledb.connect(user="myapp",password="PassworD123##",dsn="localhost:1521/FREEPDB1")

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab3_crud_operations.py<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402005592__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GB00fJuA$>:

> @@ -0,0 +1,244 @@

+import oracledb

+

+

+#connect with thick-client

+oracledb.init_oracle_client()

+connection = oracledb.connect(user="myapp",

+                              password="PassworD123##",

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab4_query_by_example.py<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402007046__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36HOChrcFQ$>:

> @@ -0,0 +1,49 @@

+import oracledb

+

+

+#connect with thick-client

+oracledb.init_oracle_client()

+connection = oracledb.connect(user="myapp",

+                              password="PassworD123##",

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab5_indexing.py<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402007652__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36G8dvXT7A$>:

> @@ -0,0 +1,56 @@

+import oracledb

+import json

+

+#connect with thick-client

+oracledb.init_oracle_client()

+connection = oracledb.connect(user="myapp",

+                              password="PassworD123##",

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab6_dbactions.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402008148__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GouwEEYg$>:

> +  Enter a number to select the database pool to update, or create an additional database pool.

+  The selected (or created) database pool will be used to install or upgrade ORDS in the database.

+    [1] default      jdbc:oracle:thin:@//localhost:1521/FREEPDB1

+    [2] Create an additional database pool

+  Choose [1]: 1

+  Enter a number to select the database connection type to use

+    [1] Basic (host name, port, service name)

+    [2] TNS (TNS alias, TNS directory)

+    [3] Custom database URL

+  Choose [1]: 1

+  Enter the database host name [localhost]:

+  Enter the database listen port [1521]:

+  Enter the database service name [FREEPDB1]:

+  Provide database user name with administrator privileges.

+    Enter the administrator username: SYS

+  Enter the database password for SYS AS SYSDBA: PassworD123##

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab6_dbactions.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402008549__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36G-veJRKg$>:

> +/

+

+exit;

+

+============== Configure the MongoDB API for later usage and Start ORDS ==============

+

+su - oracle

+ords config set mongo.enabled true

+cd /tmp

+nohup ords serve >> ords_log.log 2>&1 &

+

+

+-- Go to your browser and connect.

+http://PUBLIC_IP:8080/ords/sql-developer<https://urldefense.com/v3/__http:/PUBLIC_IP:8080/ords/sql-developer__;!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36Hnnii38A$>

+user: myapp

+password:PassworD123##

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab7_data_modeling.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402008825__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36FG9qDSJw$>:

> @@ -0,0 +1,323 @@

+============== 1) Working with SODA ==============

+

+Simple Oracle Document Access (SODA) is a set of NoSQL-style APIs that let you create and store collections of documents (in particular JSON) in Oracle Database, retrieve them, and query them, without needing to know Structured Query Language (SQL) or how the documents are stored in the database.

+

+How is data stored? Let's connect via sqlplus with root user.

+

+sqlplus ***@***.***:1521/FREEPDB1

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab7_data_modeling.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402009075__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36HBknJXxw$>:

> +When creating a SODA collection, a table is created. This table contains 4 columns for metadata, and 1 column containing the JSON information, DATA.

+

+

+2) select * from HOTEL_RESERVATIONS;

+

+We can run a select all and we can see all the information, including the JSON data. On the following lab, you will learn how to use SQL over JSON data.

+

+

+

+

+============== 2) Hybrid Model ==============

+

+We can create a table containing JSON data and relational data.

+

+

+sqlplus ***@***.***:1521/FREEPDB1

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab6_dbactions.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402010438__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36HUTkkEqQ$>:

> +  Choose [1]:

+  Enter the HTTP port [8080]:

+

+--When you see the following line, run: ctrl + c to kill ords

+

+2023-11-17T14:56:13.685Z INFO        Oracle REST Data Services initialized

+ctrl + c

+

+-- Open firewall

+exit

+firewall-cmd --permanent --zone=public --add-port=8080/tcp

+firewall-cmd --reload

+

+

+-- Enable myapp user for ORDS

+sqlplus ***@***.***:1521/FREEPDB1 as sysdba

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab7_data_modeling.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402010772__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36Gv7d3Yag$>:

> +

+

+==========================Map duality view to a python soda collection ============

+DECLARE col soda_collection_t;

+BEGIN

+  col := DBMS_SODA.create_dualv_collection('BILLING_COLLECTION', 'BILLING_DV');

+END;

+/

+============= New python code to work with collection ================

+import oracledb

+

+#thick mode for SODA

+oracledb.init_oracle_client()

+

+#connection details

+connection = oracledb.connect(user="myapp",password="PassworD123##",dsn="localhost:1521/FREEPDB1")

No hardcoded password!

________________________________

In data-platform/autonomous-database/autonomous-json/python-developer-track-oracle-json/files/lab9_mongodb_api.txt<https://urldefense.com/v3/__https:/github.com/oracle-devrel/technology-engineering/pull/612*discussion_r1402011028__;Iw!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36FLBThuMQ$>:

> @@ -0,0 +1,64 @@

+========================== Use MongoDB API with Duality views ============

+

+--Install mongodb client: https://www.mongodb.com/try/download/shell<https://urldefense.com/v3/__https:/www.mongodb.com/try/download/shell__;!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GH4-TVHw$>

+

+

+wget https://downloads.mongodb.com/compass/mongodb-mongosh-2.0.2.x86_64.rpm<https://urldefense.com/v3/__https:/downloads.mongodb.com/compass/mongodb-mongosh-2.0.2.x86_64.rpm__;!!ACWV5N9M2RV99hQ!LAMXUYsmuPcC4u-2XLUj4Br2H7VK8teTX1ezLYLvUt-GchoS2YllcXO6m2lCpciTSj-oIBso68ZKQNEDn3IutZ_m36GCqDIN_A$>

+yum localinstall mongodb-mongosh-2.0.2.x86_64.rpm

+

+--we can find the url at the ords log we defined before, and we will have something like this:

+--mongodb://[{user}:{password}@]localhost:27017/{user}?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true

+

+--It is a default string. Let's connect with our user.

+--For the password is required to change # with %23: https://docs.oracle.com/en-us/iaas/autonomous-database-serverless/doc/mongo-using-oracle-database-api-mongodb.html

+

+mongosh --tlsAllowInvalidCertificates ***@***.***:27017/myapp?authMechanism=PLAIN&authSource=$external&ssl=true&retryWrites=false&loadBalanced=true'

No hardcoded password!

**Pull request closed without merging**
