### PR TITLE
Create Multitenant

### PR DESCRIPTION
**Pull request by stephaneduprat**
Multitenant folder

### CODE REVIEW

**Review by stephaneduprat — COMMENTED** [review]
Renamed to multitenant

**Comment by AlexanderHodicke** [comment]
@stephaneduprat Please accept the CLA by commenting in your PR with:

I have read the CLA Document and I hereby sign the CLA

**Review by AlexanderHodicke — APPROVED** [review]

**Review by AlexanderHodicke — CHANGES_REQUESTED** [review]
please accept CLA

**Review by JesusGitHubOracle — APPROVED** [review]
Approved

**Review by AlexanderHodicke — APPROVED** [review]

**Pull request merged**
